### PR TITLE
Merge dev to master: support `all` for comments and rewrite to upgrade github api version

### PR DESCRIPTION
**Pull request by jlaneve**

### CODE REVIEW

**Comment by trong-le** [comment]
@jlaneve Can you resolve the merge conflicts and make sure the circle tests pass?

**Comment by jlaneve** [comment]
@trong-le yep, I'll see if I can get to that today.

**Comment by jlaneve** [comment]
@trong-le Tests are now passing. Problem was with environment variables not being loaded.

**Comment by trong-le** [comment]
@jlaneve tests look good! can you rebase the changes to master to resolve the conflicts too?

**Pull request closed without merging**
